/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pokedex.models;
import java.util.Objects;

public class PokemonModel {
    // Attribute
    private String name ;
    private int id;
    private int height;
    private int weight;
    private String description;

    // Constructor
    public PokemonModel() {
        name = "";
        id = 0;
        height = 0;
        weight = 0;
        description = "";
    }

    public PokemonModel(String name, int id, int height, int weight, String description) {
        setName(name);
        setId(id);
        setHeight(height);
        setWeight(weight);
        setDescription(description);
    }

    // Getters
    public String getName() {
        return name;
    }

    public int getId() {
        return id;
    }

    public int getHeight() {
        return height;
    }

    public int getWeight() {
        return weight;
    }

    public String getDescription() {
        return description;
    }

    // Setters
    public void setName(String name) {
        this.name = name;
    }

    public void setId(int id) {
        if (id >= 0) {
            this.id = id;
        }
    }

    public void setHeight(int height) {
        if (height >= 0) {
            this.height = height;
        }
    }

    public void setWeight(int weight) {
        if (height >= 0) {
            this.weight = weight;
        }
    }

    public void setDescription(String description){
        this.description = description;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PokemonModel that = (PokemonModel) o;
        return id == that.id &&
                height == that.height &&
                weight == that.weight &&
                Objects.equals(name, that.name) &&
                Objects.equals(description, that.description);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, id, height, weight, description);
    }
}
