/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pokedex.models;

public class PokemonModel {
    // Attribute
    private String name ;
    private int id;

    // Constructor
    PokemonModel() {
        name = "";
        id = 0;
    }

    // Getters
    public String getName() {
        return name;
    }

    public int getId() {
        return id;
    }

    // Setters
    public void setName(String name) {
        this.name = name;
    }

    public void setId(int id) {
        if (id >= 0) {
            this.id = id;
        }
    }
}
