/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pokedex.models;

public class PokemonModel {
    // Attribute
    private String name ;
    private int id;
    private int height;
    private int weight;
    private String description;

    // Constructor
    PokemonModel() {
        name = "";
        id = 0;
        height = 0;
        weight = 0;
        description = "";
    }

    // Getters
    public String getName() {
        return name;
    }

    public int getId() {
        return id;
    }

    public int getHeight() {
        return height;
    }

    public int getWeight() {
        return weight;
    }

    public String getDescription() {
        return description;
    }

    // Setters
    public void setName(String name) {
        this.name = name;
    }

    public void setId(int id) {
        if (id >= 0) {
            this.id = id;
        }
    }

    public void setHeight(int height) {
        if (height >= 0) {
            this.height = height;
        }
    }

    public void setWeight(int weight) {
        if (height >= 0) {
            this.weight = weight;
        }
    }

    public void setDescription(String description){
        this.description = description;
    }
}
