/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pokedex;

import pokedex.controllers.PokemonController;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        if (args.length != 1) {
            System.out.println("Please provide a Pokémon ID as an argument.");
            return;
        }

        int pokemonId = Integer.parseInt(args[0]);

        PokemonController controller = new PokemonController();
        controller.setPokemon(pokemonId);
        controller.showPokemon();
    }
}
