/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pokedex.models;

import org.junit.Test;
import static org.junit.Assert.*;

public class PokemonModelTest {

    private PokemonModel pokemon;

    @BeforeEach
    public void setUp() {
        pokemon = new PokemonModel();
    }

    @Test public void testSetName() {
        pokemon.setName("Bulbizare");
        assertEquals("Bulbizzare", pokemon.getName());
    }
}
