/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pokedex.models;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import static org.junit.jupiter.api.Assertions.*;

import java.lang.annotation.Target;

public class PokemonApiClientTest {

    private PokemonApiClient api;

    @BeforeEach public void setUp() {
        api = new PokemonApiClient();
    }
}
