/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pokedex.models;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import static org.junit.jupiter.api.Assertions.*;

import java.lang.annotation.Target;

public class PokemonApiClientTest {

    private PokemonApiClient api;

    @BeforeEach public void setUp() {
        api = new PokemonApiClient();
    }

    @Test public void testGetPokemonInfoTest() {
        PokemonModel pokemon = new PokemonModel("bulbasaur",1,7,69,"");
        PokemonModel apiPokemon = api.getPokemonInfo(1);
        assertEquals(pokemon,apiPokemon);
    }

    @Test public void testGetPokemonInfoWithInvalidId() {
        PokemonModel apiPokemonModel = api.getPokemonInfo(-1);
        assertEquals(null, apiPokemonModel);
    }
}
